### ISSUE TITLE
State-Machine-Role is not authorized to perform: lambda:InvokeFunction on resource Input-File-Checker

### ISSUE THREAD

**Issue by yoyu777** [yoyu777/ml-demo#1]

**Comment by Praveenk8051** [comment]
Is it already solved?

**Comment by Praveenk8051** [comment]
I'm still facing the error!

**Comment by yoyu777** [comment]
Hi, this is fixed in pull request #3.
You can check if your state machine role has the permission to invoke lambda function (https://github.com/yoyu777/ml-demo/pull/3/commits/fd05ed5e1c75d63e005cc7f4a770883616e8d0c8)

**Comment by Praveenk8051** [comment]
Actually I was creating my own role to Invoke Lambda and assigning it to Step function. When I used 'Let Step Function create IAM role' it worked fine..
